### ISSUE TITLE
username font

### ISSUE THREAD

**Issue by prophetnite** [HatCrew/HatClient#1]
Looks like shit.  Font for messages looks nice, but username font just doesn't feel right.

**Comment by PASwd4** [comment]
Any suggestions? I prefer using fonts from [Google Fonts](https://fonts.google.com)

**Comment by PASwd4** [comment]
Font for messages and chatInput has been updated to Roboto Mono.

**EDIT:** It would appear that I misread your comment, I'll fix this soon.
